# -*- coding: utf-8 -*-
"""Practica05LC.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P_tK3mKHc8KVQwZ9rTBk1CqhYqVUkEYc

---
# **Práctica 5**: *Fine-tunning y puesta en producción de modelos*
---
### **Alumno**:  Roberto Samuel Sanchez Rosas
"""

#Instalación de dependencias
!pip install transformers datasets evaluate codecarbon accelerate seqeval -q

# Importaciones y Activación de CodeCarbon

import os
import numpy as np
import evaluate
from datasets import load_dataset
from transformers import AutoTokenizer, AutoModelForTokenClassification
from transformers import TrainingArguments, Trainer, DataCollatorForTokenClassification
from codecarbon import EmissionsTracker

# Creamos explícitamente el directorio si no existe
output_dir_metrics = "./output_metrics"
if not os.path.exists(output_dir_metrics):
    os.makedirs(output_dir_metrics)
    print(f"Carpeta '{output_dir_metrics}' creada exitosamente.")

# Inicializamos el rastreador ambiental para el reporte de sustentabilidad
tracker = EmissionsTracker(output_dir=output_dir_metrics, log_level="error")
tracker.start()
print("Rastreador CodeCarbon activado para monitorear el Fine-Tuning.")

# Carga del Dataset de NER y Configuración del Modelo Base

checkpoint = "albert-base-v2"

# CoNLL-2003, dataset estándar para reconocimiento de entidades
raw_datasets = load_dataset("eriktks/conll2003",revision="convert/parquet")

# Extraemos las etiquetas originales del dataset (PER, LOC, ORG, MISC)
label_list = raw_datasets["train"].features["ner_tags"].feature.names

# Creamos diccionarios de mapeo indispensables para la tarea *ForTokenClassification
id2label = {i: label for i, label in enumerate(label_list)}
label2id = {label: i for i, label in enumerate(label_list)}

print(f"Dataset CoNLL-2003 cargado con éxito.")
print(f"Etiquetas del sistema NER: {label_list}")

# Tokenización y Alineación de Etiquetas

tokenizer = AutoTokenizer.from_pretrained(checkpoint)

def tokenize_and_align_labels(examples):
    # Tokenizamos las palabras ya pre-divididas del dataset
    tokenized_inputs = tokenizer(examples["tokens"], truncation=True, is_split_into_words=True, max_length=512)

    labels = []
    for i, label in enumerate(examples["ner_tags"]):
        word_ids = tokenized_inputs.word_ids(batch_index=i)
        previous_word_idx = None
        label_ids = []

        for word_idx in word_ids:
            # Los tokens especiales de mapeo (como [CLS] o [SEP]) reciben un ID de -100 para ignorarlos en la pérdida
            if word_idx is None:
                label_ids.append(-100)
            # Si el subtoken pertenece a la misma palabra anterior, le asignamos la misma etiqueta o la ignoramos
            elif word_idx != previous_word_idx:
                label_ids.append(label[word_idx])
            else:
                label_ids.append(label[word_idx])
            previous_word_idx = word_idx

        labels.append(label_ids)

    tokenized_inputs["labels"] = labels
    return tokenized_inputs

# Aplicamos la alineación en nuestros conjuntos de datos
tokenized_datasets = raw_datasets.map(tokenize_and_align_labels, batched=True)

# Data Collator específico para Token Classification
data_collator = DataCollatorForTokenClassification(tokenizer=tokenizer)
print("Tokenización y alineación de subtokens completada de forma óptima.")

# Definición de Métricas con Seqeval (Métricas específicas para NER)

# Cargamos la métrica seqeval, diseñada para evaluar secuencias de etiquetas completas
metric = evaluate.load("seqeval")

def compute_metrics(p):
    predictions, labels = p
    predictions = np.argmax(predictions, axis=-1)

    # Removemos los índices ignorados (-100) para calcular métricas reales
    true_predictions = [
        [id2label[p] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]
    true_labels = [
        [id2label[l] for (p, l) in zip(prediction, label) if l != -100]
        for prediction, label in zip(predictions, labels)
    ]

    results = metric.compute(predictions=true_predictions, references=true_labels)
    return {
        "precision": results["overall_precision"],
        "recall": results["overall_recall"],
        "f1": results["overall_f1"],
        "accuracy": results["overall_accuracy"],
    }

# Configuración de la Arquitectura AlbertForTokenClassification y Trainer

# AutoModel instanciará automáticamente un AlbertForTokenClassification usando los mapeos creados
model = AutoModelForTokenClassification.from_pretrained(
    checkpoint,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

training_args = TrainingArguments(
    output_dir="albert-finetuned-ner",
    learning_rate=2e-5,
    per_device_train_batch_size=16,
    per_device_eval_batch_size=16,
    num_train_epochs=3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    report_to="none"
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_datasets["train"].shuffle(seed=42).select(range(4000)),
    eval_dataset=tokenized_datasets["validation"].shuffle(seed=42).select(range(500)),
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

print("Iniciando Fine-Tuning de ALBERT para Clasificación de Tokens (NER)...")
trainer.train()

# Cierre del Monitoreo y Guardado Local del Modelo

emissions = tracker.stop()
print(f"\n¡Fine-Tuning finalizado de forma exitosa!")
print(f"Emisiones estimadas del entrenamiento individual: {emissions * 1000:.4f} g de CO2")

# Guardamos el modelo final y el tokenizador en una carpeta local
trainer.save_model("./modelo_ner_albert")
tokenizer.save_pretrained("./modelo_ner_albert")
print("Modelo y configuraciones exportadas localmente.")

# Comprimimos para descargar o pasar directamente al Space de Hugging Face
!zip -r modelo_ner_albert.zip ./modelo_ner_albert